# Generated by Django 4.2.23 on 2025-07-24 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id_clases', models.IntegerField(primary_key=True, serialize=False)),
                ('materia', models.IntegerField(verbose_name='ID Materia')),
                ('docente', models.IntegerField(blank=True, null=True, verbose_name='ID Docente')),
                ('horario', models.CharField(max_length=100, verbose_name='Horario')),
                ('aula_clase', models.CharField(max_length=70, verbose_name='Aula')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'db_table': 'clases',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=100, verbose_name='Número de matrícula')),
                ('carrera', models.CharField(max_length=100, verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'estudiante',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MateriaClase',
            fields=[
                ('id_materia_clases', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_materia', models.CharField(max_length=100, verbose_name='Nombre de la materia')),
                ('codigo_materia', models.CharField(max_length=100, verbose_name='Código de materia')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'db_table': 'materia_clases',
                'ordering': ['codigo_materia'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('password_hash', models.CharField(max_length=100, verbose_name='Hash de contraseña')),
                ('rol', models.CharField(max_length=100, verbose_name='Rol del usuario')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pagos', models.OneToOneField(db_column='id_pagos', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='pago', serialize=False, to='AppCRM.estudiante')),
                ('id_usuario', models.IntegerField()),
                ('id_transacion', models.CharField(max_length=255, verbose_name='ID de transacción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('moneda', models.CharField(max_length=20, verbose_name='Moneda')),
                ('estado_pago', models.CharField(max_length=50)),
                ('metodo_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del pago')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id_inscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('clase', models.IntegerField(verbose_name='ID Clase')),
                ('fecha_inscripcion', models.DateTimeField(blank=True, null=True)),
                ('id_estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.DO_NOTHING, related_name='inscripciones', to='AppCRM.usuario')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'db_table': 'inscripcion',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, related_name='estudiante_perfil', to='AppCRM.usuario'),
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre_docente', models.CharField(max_length=100, verbose_name='Nombre del docente')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('especialidad', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, related_name='docente_perfil', to='AppCRM.usuario')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'db_table': 'docente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id_calificaciones', models.IntegerField(primary_key=True, serialize=False)),
                ('clase', models.IntegerField(verbose_name='ID Clase')),
                ('notas', models.DecimalField(decimal_places=65535, max_digits=65535, verbose_name='Calificación')),
                ('tipo_evaluacion', models.CharField(max_length=50, verbose_name='Tipo de evaluación')),
                ('id_estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.DO_NOTHING, related_name='calificaciones', to='AppCRM.usuario')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'db_table': 'calificacione',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_adimin', models.AutoField(primary_key=True, serialize=False)),
                ('puesto', models.CharField(max_length=100, verbose_name='Puesto administrativo')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, related_name='administrador_perfil', to='AppCRM.usuario')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'db_table': 'admin',
                'managed': True,
            },
        ),
    ]
