# Generated by Django 4.2.23 on 2025-08-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCRM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.DurationField(blank=True, null=True, verbose_name='ultimo login '),
        ),
    ]
